kind: RoleBinding
apiVersion: rbac.authorization.k8s.io/v1
metadata:
  name: rag4-port-aug13-1-dsp-job-rolebinding
subjects:
  - kind: ServiceAccount
    name: rag4-port-aug13-1-dsp-job
    namespace: rag4-port-aug13-1
roleRef:
  apiGroup: rbac.authorization.k8s.io
  kind: Role
  name: rag4-port-aug13-1-dsp-job-role